# Generated by Django 4.0.1 on 2022-01-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsystem', '0007_alter_comment_author_user_alter_issue_assignee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='itsystem.issue'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('auteur', 'auteur'), ('contributeur', 'contributeur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('faible', 'faible'), ('moyenne', 'moyenne'), ('élevée', 'élevée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('a faire', 'a faire'), ('en cours', 'en Cours'), ('terminé', 'terminé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('bug', 'bug'), ('amélioration', 'amélioration'), ('tâche', 'tâche')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_project',
            field=models.CharField(choices=[('back-end', 'back-end'), ('front-end', 'front-end'), ('ios', 'ios'), ('android', 'android')], max_length=20),
        ),
    ]
