# Generated by Django 4.0.1 on 2022-01-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itsystem', '0008_alter_comment_issue_alter_contributor_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='itsystem.project'),
        ),
    ]
